config/routes.rb
Courses::Application.routes.draw do
  get "home/index"
  get "home/requests"
  get "slides/show"

  devise_for :users

  resources :courses do
    member do
      get 'policies'
      post 'policies'
      get 'grade_thresholds'
      post 'grade_thresholds'
      get 'time_cards'
      post 'time_cards'
      post 'enroll'
      post 'register'
      get 'set_feedback_questions'
      patch 'set_feedback_questions'
    end
    collection do
      get 'new_options'
      get 'copy'
      post 'copy'
    end
  end
  resources :course_students do
    member do
      patch 'approve'
      get 'change_email'
      patch 'change_email'
      get 'change_password'
      patch 'change_password'
      get 'change_code'
      patch 'change_code'
    end
  end
  resources :schools
  resources :terms
  resources :users do
    member do
      post 'approve_as_instructor'
      post 'reject_as_instructor'
      get 'new_student'
      post 'create_student'
    end
  end
  resources :assignments do
    member do
      post 'turn_in'
      get 'grade'
      post 'grade'
      get 'grade_matrix'
      post 'grade_matrix'
      get 'view_grades'
    end
  end
  resources :achievements do
    collection do
      get 'award'
      post 'award'
    end
  end
  resources :lessons do
    collection do
      get 'schedule'
    end
  end
  resources :meetings do
    member do
      get 'lead_in_question'
      get 'outline'
      get 'media'
      get 'provide_feedback'
      post 'provide_feedback'
    end
    collection do
      post 'create_many'
    end
  end
  resources :meeting_lessons do
    member do
      delete 'destroy_and_shift'
    end
  end

  root 'home#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :course
  has_many :meeting_lessons, -> {order :order_number, :lesson_id}, dependent: :destroy
  has_many :lessons, through: :meeting_lessons
  has_many :feedback_answers, dependent: :destroy

  default_scope { order('held_at') }

  validates :held_at, presence: true
  validates :video_url, format: {with: /\Ahttps?:\/\//, message: "must start with http:// or https://"}, allow_blank: true

  delegate :code_and_name, to: :course, prefix: true

  after_update :update_all_lesson_activity_times
  after_destroy :update_nearby_lesson_activity_times

  def provide_feedback(scores_hash, user)
    course_student = CourseStudent.where(student: user, course: course).first
    scores_hash.each do |k, v|
      feedback_answers << FeedbackAnswer.new(course_student: course_student,
        feedback_question: FeedbackQuestion.find(k),
        score: v)
    end
    save!
  end

  def feedback_exists_for_user?(user)
    course_student = CourseStudent.where(student: user, course: course).first
    FeedbackAnswer.where(meeting: self, course_student: course_student).present?
  end

  def update_all_lesson_activity_times
    if held_at_changed?
      course.lessons.each {|l| l.update_activity_times}
    end
  end

  def update_nearby_lesson_activity_times
    if preceding_meeting
      preceding_meeting.lessons.each {|l| l.update_activity_times}
    end
    lessons.each {|l| l.update_activity_times}
    if next_meeting
      preceding_meeting.lessons.each {|l| l.update_activity_times}
    end
  end

  def has_slides?
    lessons.each do |l|
      return true unless l.slide_html.blank?
    end
    false
  end

  def in_past?
    held_at < Time.now
  end

  def next_meeting?
    self == course.next_meeting
  end

  def in_future?
    held_at > Time.now
  end

  def past_or_next?
    in_past? || next_meeting?
  end

  def lesson_names
    lessons.map(&:name).join(', ')
  end

  def held_at_integer
    held_at.to_i
  end

  def preceding_meeting
    course.meetings.where("held_at < ?", held_at).order("held_at DESC").first
  end

  def preceding_meeting_held_at
    preceding_meeting ? preceding_meeting.held_at : course.term.starts_on
  end

  def next_meeting
    course.meetings.where("held_at > ?", held_at).order("held_at").first
  end

  def next_meeting_held_at
    next_meeting ? next_meeting.held_at : course.term.ends_on
  end

  def average_feedback(feedback_question)
    scores = feedback_answers.where(feedback_question: feedback_question).map &:score
    scores.blank? ? nil : (scores.sum / scores.count)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!, except: [:lead_in_question, :media]
  before_action :set_meeting, only: [:edit, :update, :destroy, :lead_in_question, :outline, :media, :provide_feedback]
  before_action :set_course
  before_action :instructor_only!, except: [:lead_in_question, :media, :provide_feedback]

  # GET/POST
  def provide_feedback
    if @meeting.feedback_exists_for_user?(current_user)
      redirect_to @course, flash: {error: 'You have already submitted feedback for this day.'}
    elsif request.post?
      @meeting.provide_feedback(params[:questions], current_user)
      redirect_to @course, flash: {success: 'Thank you for your feedback!'}
    end
  end

  # GET
  def lead_in_question
  end

  # GET
  def outline
  end

  # GET
  def media
  end

  # GET
  def index
    @meetings = @course.meetings
  end


  # GET
  def edit
  end

  # POST
  def create
    @meeting = Meeting.new(held_at: params[:held_at], course_id: @course.id)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path(course_id: @course.id), flash: {success: 'Meeting was successfully created.'} }
      else
        format.html { redirect_to meetings_path(course_id: @course.id), flash: {error: 'Meeting failed to save.  Try again.'} }
      end
    end
  end


  # POST
  def create_many
    start_date   = params[:start_date].to_date
    end_date     = params[:end_date].to_date
    days_of_week = params[:day].map {|k, v| v.to_i}

    respond_to do |format|
      if @course.create_series_of_meetings(start_date, end_date, params[:time_of_day], days_of_week)
        format.html { redirect_to meetings_path(course_id: @course.id), flash: {success: 'Meetings were successfully created.'} }
      else
        format.html { redirect_to meetings_path(course_id: @course.id), flash: {error: 'Meetings failed to save.  Try again.'} }
      end
    end
  end


  # PATCH/PUT
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to params[:redirect] || meetings_path(course_id: @course.id), flash: {success: 'Meeting was successfully updated.'} }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_path(course_id: @course.id), notice: 'Meeting was successfully deleted.' }
    end
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def set_course
      @course = (@meeting ? @meeting.course : Course.find(params[:course_id]))
    end

    def meeting_params
      params.require(:meeting).permit(:course_id, :held_at, :video_url)
    end
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :redirect, params[:redirect] %>

  <%= f.hidden_field :course_id %>

  <%= f.label :held_at do %>
    <span class="field-label">Meeting Time</span> <%= f.text_field :held_at, required: true %>
    <span class="help-inline">e.g. "<%= Date.today %> 14:00"</span>
  <% end %>

  <% if @course.use_meeting_video %>
    <%= f.label :video_url do %>
      <span class="field-label">Video URL</span> <%= f.text_field :video_url, class: 'input-xxlarge',
         placeholder: "(must start with http or https)" %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/meetings/_meeting_list.html.erb
<div class="meeting-list">
  <% @meetings.each do |m| %>
    <div class="meeting-time">
      <span class="meeting-time-day">
        <i class="fa fa-clock-o"></i>
        <%= weekday_abbreviation(m.held_at) %>
      </span>
      <% if editable %>
        <span class="meeting-time-long-date muted"><%= date_humanized(m.held_at) %></span>
        <span class="meeting-time-time muted"><%= time_abbreviation(m.held_at) %></span>
        <span class="meeting-time-icons">
          <a href="#edit-meeting-<%= m.id %>-modal" data-toggle="modal"><i class="fa fa-pencil"></i></a>
          <%= link_to '<i class="fa fa-times text-error"></i>'.html_safe, m, method: :delete,
            data: { confirm: "Are you sure you'd like to delete this meeting time?" } %>
        </span>
        <%= render partial: '/meetings/modal_edit_meeting', locals: {meeting: m} %>
      <% else %>
        <span class="meeting-time-date muted"><%= date_abbreviation(m.held_at) %></span>
        <% if m.lessons.blank? %>
        <span class="muted">No Lessons</span>
        <% else%>
          <% m.meeting_lessons.each do |ml| %>
            <span class="label label-info">
              <%= ml.lesson_name %>
              <a href="#remove-meeting-lesson-<%= ml.id %>-modal" data-toggle="modal"><i class="fa fa-times-circle white"></i></a>
            </span>
            <%= render partial: '/meetings/modal_remove_meeting_lesson', locals: {meeting_lesson: ml} %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if editable %>
    <br/>
    <a href="#new-meeting-modal" class="meeting-time" data-toggle="modal">
      <span class="btn btn-success"><i class="fa fa-plus"></i> Add Meeting Time(s)</span>
    </a>
    <%= render partial: 'modal_new_meeting' %>
  <% end %>
</div>

app/views/meetings/_modal_edit_meeting.html.erb
<div id="edit-meeting-<%= meeting.id %>-modal" class="modal hide fade">
  <%= form_for meeting do |f| %>
    <div class="modal-header">
      <h3>Edit Meeting</h3>
    </div>
    <div class="modal-body">
      <span class="field-label">Date/Time</span>
      <%= f.text_field :held_at, required: true, value: db_datetime_string(meeting.held_at) %>
      <span class="help-inline">e.g. "<%= Date.today %> 14:00"</span>
    </div>
    <div class="modal-footer">
      <a class="btn" data-dismiss="modal">Close</a>
      <%= submit_tag "Save Meeting Time", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/meetings/_modal_edit_meeting_or_lessons.html.erb
<div id="edit-meeting-<%= meeting.id %>-modal" class="modal hide fade">
  <div class="modal-header text-left">
    <h3>Edit Meeting or Edit Lessons?</h3>
  </div>
  <div class="modal-body text-left">
    <p class="lead">Meeting Time
      <% if @course.use_meeting_video %>
        (and Video URL)
      <% end %>
    </p>
    <p><%= link_to "<i class='fa fa-clock-o'></i> Edit Meeting".html_safe, edit_meeting_path(meeting, redirect: course_path(@course)), class: "btn" %></p>

    <p class="lead"><%= meeting.lessons.count == 1 ? "Lesson" : "Lessons" %></p>
    <% if meeting.lessons.present? %>
      <% meeting.lessons.each do |l| %>
        <p><%= link_to "<i class='fa fa-compass'></i> Edit Lesson: ".html_safe + l.name, edit_lesson_path(l, redirect: course_path(@course)), class: "btn" %></p>
      <% end %>
    <% else %>
      <p class="muted">
        No lessons scheduled for this meeting time yet.
        <%= link_to "Schedule them.", schedule_lessons_path(course_id: @course.id) %>
      </p>
    <% end %>
  </div>
  <div class="modal-footer">
    <a class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/meetings/_modal_new_meeting.html.erb
<div id="new-meeting-modal" class="modal hide fade">

  <div class="modal-header">
    <h3>Add Meeting Times to <%= @course.course_code %></h3>
  </div>

  <%= form_tag meetings_path, method: :post do %>
    <div class="modal-body">
      <p>To add one meeting time, enter the date and time here.</p>
      <%= hidden_field_tag :course_id, @course.id %>
      <span class="field-label"><%= label_tag :held_at, "Date/Time" %></span>
      <%= text_field_tag :held_at, nil, required: true %>
      <span class="help-inline">e.g. "<%= @course.term_starts_on %> 14:00"</span>
    </div>
    <div class="modal-footer">
      <%= submit_tag "Add One Meeting Time", class: "btn btn-success" %>
    </div>
  <% end %>

  <%= form_tag create_many_meetings_path, method: :post do %>
    <div class="modal-body">
      <p>To add the same meeting times every week, check the days of the week,
        enter a start date, an end date, and the time of day.</p>
      <%= hidden_field_tag :course_id, @course.id %>
      <div class="days-of-week">
        <%= check_box_tag "day[1]", "1" %> M
        <%= check_box_tag "day[2]", "2" %> T
        <%= check_box_tag "day[3]", "3" %> W
        <%= check_box_tag "day[4]", "4" %> Th
        <%= check_box_tag "day[5]", "5" %> F
        <%= check_box_tag "day[6]", "6" %> S
        <%= check_box_tag "day[0]", "0" %> Su
      </div>
      <span class="field-label"><%= label_tag :held_at, "Start Date" %></span>
      <%= text_field_tag :start_date, @course.term_starts_on, required: true %>
      <span class="help-inline">e.g. "<%= @course.term_starts_on %>"</span>
      <span class="field-label"><%= label_tag :held_at, "End Date" %></span>
      <%= text_field_tag :end_date, @course.term_ends_on, required: true %>
      <span class="help-inline">e.g. "<%= @course.term_ends_on %>"</span>
      <span class="field-label"><%= label_tag :held_at, "Time of Day" %></span>
      <%= text_field_tag :time_of_day, "14:00", required: true, class: "input-small" %>
      <span class="help-inline">e.g. "14:00"</span>
    </div>
    <div class="modal-footer">
      <a class="btn" data-dismiss="modal">Close</a>
      <%= submit_tag "Add Repeating Meeting Times", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/meetings/_modal_remove_meeting_lesson.html.erb
<div id="remove-meeting-lesson-<%= meeting_lesson.id %>-modal" class="modal hide fade">
  <div class="modal-header">
    <h3><%= date_abbreviation(meeting_lesson.held_at) %> - <%= meeting_lesson.lesson_name %></h3>
  </div>
  <div class="modal-body">
    <p><%= link_to 'Remove Lesson', meeting_lesson,
          method: :delete, class: 'btn btn-danger' %></p>

    <p><%= link_to 'Remove Lesson and Shift Later Lessons Up', destroy_and_shift_meeting_lesson_path(meeting_lesson),
          method: :delete, class: 'btn btn-danger' %></p>

    <p><a class="btn" data-dismiss="modal">Cancel</a></p>
  </div>
</div>

app/views/meetings/_row_buttons.html.erb
<% if @course.use_daily_questions %>
  <% if meeting.past_or_next? %>
    <%= link_to '<i class="fa fa-edit" title="Pre-class Readings and Questions"></i>'.html_safe, lead_in_question_meeting_path(meeting) %>
  <% else %>
    <i class="fa fa-edit muted" title="Pre-class Readings and Questions"></i>
  <% end %>
<% end %>

<% if @course.use_course_feedback && current_user && current_user.enrolled?(@course)%>
  <% if meeting.in_past? %>
    <%= link_to '<i class="fa fa-comment-o" title="Provide Feedback"></i>'.html_safe, provide_feedback_meeting_path(meeting) %>
  <% else %>
    <i class="fa fa-comment-o muted" title="Provide Feedback"></i>
  <% end %>
<% end %>

<% if meeting.in_past? %>
  <%= link_to '<i class="fa fa-cloud-download" title="Lesson Media"></i>'.html_safe, media_meeting_path(meeting) %>
<% else %>
  <i class="fa fa-cloud-download muted" title="Lesson Media"></i>
<% end %>

<% if @course.use_reveal_slides %>
  <% if meeting.has_slides? && ((current_user && current_user.teaching?(@course)) || meeting.in_past?) %>
    <%= link_to '<i class="fa fa-laptop" title="Lesson Slides"></i>'.html_safe, slides_show_path(meeting_id: meeting.id), target: "blank" %>
  <% else %>
    <i class="fa fa-laptop muted" title="Lesson Slides"></i>
  <% end %>
<% end %>

<% if @course.use_meeting_video %>
  <% if meeting.in_past? && meeting.video_url.present? %>
    <%= link_to '<i class="fa fa-film" title="Lesson Video"></i>'.html_safe, meeting.video_url, target: 'blank' %>
  <% else %>
    <i class="fa fa-film muted" title="Lesson Video"></i>
  <% end %>
<% end %>

<% if current_user && current_user.teaching?(@course) %>
  <%= link_to '<i class="fa fa-list-ul" title="Lesson Outlines"></i>'.html_safe, outline_meeting_path(meeting) %>
  <a href="#edit-meeting-<%= meeting.id %>-modal" class="btn btn-mini" data-toggle="modal">Edit</a>
  <%= render partial: "/meetings/modal_edit_meeting_or_lessons", locals: {meeting: meeting} %>
<% end %>

app/views/meetings/edit.html.erb
<p><%= link_to back_arrow + "Back to #{@meeting.course_code_and_name}", @meeting.course %></p>

<h2><%= @meeting.course_code_and_name %> - <%= date_humanized(@meeting.held_at) %></h2>

<%= render 'form' %>

app/views/meetings/index.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>STEP 1: Create Meeting Times</h2>

<p class="lead">
  Before you can proceed with lesson planning, you must set up at least one of the times at which your course will meet.
</p>

<%= render partial: "meeting_list", locals: {editable: true} %>

<%= link_to 'Continue with Scheduling', schedule_lessons_path(course_id: @course.id), class: "btn" %>

app/views/meetings/lead_in_question.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>Daily Readings and Questions for <%= date_humanized(@meeting.held_at) %></h2>


<% if @meeting.lessons.blank? %>
  <p class="muted">No lessons scheduled during this meeting.</p>
<% end %>

<% @meeting.lessons.each do |l| %>
  <p class="lead"><%= l.name %></p>

  <p>Pre-class Readings:</p>
  <ul>
    <% if l.readings.pre.each do |r| %>
      <li><%= r.url? ? (link_to r.caption, r.url, target: "blank") : r.caption %></li>
    <% end.empty? %>
      <li class='muted'>No readings for this lesson.</li>
    <% end %>
  </ul>

  <p>Pre-class Questions:</p>
  <ul>
    <% if l.lead_in_question.present? %>
      <li><%= markdown(l.lead_in_question) %></li>
    <% else %>
      <li class='muted'>No questions for this lesson.</li>
    <% end %>
  </ul>

  <br/>
<% end %>

app/views/meetings/media.html.erb
<p><%= link_to back_arrow + "Back to #{@meeting.course_code_and_name}", @meeting.course %></p>

<h2>Media for <%= date_humanized(@meeting.held_at) %></h2>

<% unless @meeting.video_url.blank? %>
  <p class="lead">Class Video</p>

  <div class="media">
    <div class="pull-left">
      <i class="media-object fa fa-film"></i>
    </div>
    <div class="media-body">
      <h4 class="media-heading">Class Video</h4>
      <a href="<%= @meeting.video_url %>" target="blank"><%= @meeting.video_url %></a>
    </div>
  </div>

  <br/>
<% end %>


<% if @meeting.lessons.blank? %>
  <p class="muted">No lessons scheduled during this meeting.</p>
<% end %>

<% @meeting.lessons.each do |l| %>
  <p class="lead"><%= l.name %></p>

  <% if l.readings.blank? %>
    <p class="muted">No media for this lesson.</p>
  <% end %>
  <% l.readings.each do |r| %>
    <div class="media">
      <div class="pull-left">
        <i class="media-object fa <%= r.url.present? ? 'fa-cloud-download' : 'fa-book' %>"></i>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= r.caption %></h4>
        <a href="<%= r.url %>" target="blank"><%= r.url %></a>
      </div>
    </div>
  <% end %>

  <br/>
<% end %>

app/views/meetings/outline.html.erb
<p><%= link_to back_arrow + "Back to #{@meeting.course_code_and_name}", @meeting.course %></p>

<h2>Outlines for <%= date_humanized(@meeting.held_at) %></h2>

<% @meeting.lessons.each do |l| %>
  <p class="lead"><%= l.name %></p>
  <%= markdown(l.outline || "<span class='muted'>No outline for this lesson.</span>") %>
  <br/>
<% end %>

app/views/meetings/provide_feedback.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>Provide Feedback for <%= date_humanized(@meeting.held_at) %></h2>

<% if @course.feedback_questions.blank? %>
  <p class="muted">There are no feedback questions set up for this class.  Please tell the instructor!</p>
<% else %>

  <%= form_tag do %>

    <% @course.feedback_questions.each do |fq| %>
      <p class="lead"><%= fq.question %></p>
      <table class="lykert">
        <tr>
          <% 0.upto(10).each do |i| %>
            <td>
              <%= radio_button_tag("questions[#{fq.id}]", i, i==5) %>
              <br/>
              <%= i %>
              <br/>
              <span class="muted"> <%= i==0 ? "Worst" : "" %> <%= i==10 ? "Best" : "" %> </span>
            </td>
          <% end %>
        </tr>
      </table>
      <div class="spacer"></div>
    <% end %>

   <p><%= submit_tag "Submit Feedback", class: "btn" %></p>

  <% end %>

<% end %>