config/routes.rb
Courses::Application.routes.draw do
  get "home/index"
  get "home/requests"
  get "slides/show"

  devise_for :users

  resources :courses do
    member do
      get 'policies'
      post 'policies'
      get 'grade_thresholds'
      post 'grade_thresholds'
      get 'time_cards'
      post 'time_cards'
      post 'enroll'
      post 'register'
      get 'set_feedback_questions'
      patch 'set_feedback_questions'
    end
    collection do
      get 'new_options'
      get 'copy'
      post 'copy'
    end
  end
  resources :course_students do
    member do
      patch 'approve'
      get 'change_email'
      patch 'change_email'
      get 'change_password'
      patch 'change_password'
      get 'change_code'
      patch 'change_code'
    end
  end
  resources :schools
  resources :terms
  resources :users do
    member do
      post 'approve_as_instructor'
      post 'reject_as_instructor'
      get 'new_student'
      post 'create_student'
    end
  end
  resources :assignments do
    member do
      post 'turn_in'
      get 'grade'
      post 'grade'
      get 'grade_matrix'
      post 'grade_matrix'
      get 'view_grades'
    end
  end
  resources :achievements do
    collection do
      get 'award'
      post 'award'
    end
  end
  resources :lessons do
    collection do
      get 'schedule'
    end
  end
  resources :meetings do
    member do
      get 'lead_in_question'
      get 'outline'
      get 'media'
      get 'provide_feedback'
      post 'provide_feedback'
    end
    collection do
      post 'create_many'
    end
  end
  resources :meeting_lessons do
    member do
      delete 'destroy_and_shift'
    end
  end

  root 'home#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course
  has_many :assignment_questions, -> {order :order_number}, dependent: :destroy
  has_many :assignment_grades, dependent: :destroy

  validates :course_id, presence: true
  validates :name, presence: true
  validates :active_at, presence: true
  validates :due_at, presence: true
  validates :percent_of_grade, presence: true

  validate :active_no_later_than_due?

  scope :active_for_students, -> { where("active_at <= ? AND due_at >= ? AND students_can_submit = ?", Time.now, Time.now, true) }

  delegate :code_and_name, :color, to: :course, prefix: true

  accepts_nested_attributes_for :assignment_questions,
      :allow_destroy => true,
      :reject_if     => :all_blank

  def active_no_later_than_due?
    if active_at? && due_at? && active_at > due_at
      errors.add(:active_at, "must be no later than due at.")
    end
  end

  def status(user = nil)
    AssignmentStatus.new(assignment: self, user: user)
  end

  def turn_in(answers, user, final=true)
    if can_be_turned_in_by(user)
      course_student = CourseStudent.where(student: user, course: course).first
      assignment_grade = AssignmentGrade.where(assignment: self,
        course_student: course_student).first_or_create!

      assignment_grade.submitted_at = Time.now if final

      unless answers.blank?
        answers.each do |k,v|
          aqg = AssignmentQuestionGrade.where(assignment_question_id: k.to_i,
            assignment_grade: assignment_grade).first_or_create!
            aqg.answer = v
            aqg.save!
        end
      end

      assignment_grade.save!
    end
  end

  def can_be_turned_in_by(user)
    students_can_submit && user && user.enrolled?(course) && status(user).overdue_or_in_progress?
  end

  def has_been_answered_by(user)
    if user
      if (course_student = CourseStudent.where(student: user, course: course).first)
        assignment_grades.where(course_student_id: course_student.id).first
      end
    end
  end

  def letter_grade_for(user)
    if (assignment_grade = has_been_answered_by(user))
      assignment_grade.letter_grade
    end
  end

  def copy_with_questions(new_course)
    new_assignment = dup
    new_assignment.course = new_course
    new_assignment.due_at = shift_by_years(due_at)
    new_assignment.active_at = [shift_by_years(active_at), new_assignment.due_at].min
    new_assignment.save!

    new_assignment.assignment_questions = assignment_questions.map {|aq| aq.dup}
    new_assignment.save!
    new_assignment
  end

  private

  def shift_by_years(old_date)
    new_date = old_date
    while new_date < Time.now do
      new_date += 1.year
    end
    new_date
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_assignment_and_course, only: [:show, :edit, :update, :destroy, :turn_in, :grade, :grade_matrix, :view_grades]
  before_action :set_course, only: [:new, :create]
  before_action :instructor_only!, except: [:show, :turn_in]

  # GET
  def show
  end

  # GET
  def new
    if params[:lesson_id]
      @lesson = Lesson.find(params[:lesson_id])
    end

    @assignment = Assignment.new
    @assignment.course_id = @course.id

    #Build new question so that more can be added w/o JS.
    @assignment.assignment_questions.build
  end

  # GET
  def edit
    if (@lesson = Lesson.linked_to_assignment(@assignment))
      params[:in_class] = @lesson.correct_in_class_assignment?(@assignment)
    end
    @assignment.assignment_questions.build
  end

  # POST
  def create
    @assignment = Assignment.new(assignment_params)

    if params[:lesson_id]
      @lesson = Lesson.find(params[:lesson_id])
      @assignment.name = @lesson.activity_name(params[:in_class].to_bool)
      @assignment.active_at = @lesson.activity_active_at(params[:in_class].to_bool)
      @assignment.due_at = @lesson.activity_due_at(params[:in_class].to_bool)
    end

    respond_to do |format|
      Assignment.transaction do
        if @assignment.save
          if @lesson
            @lesson.send((params[:in_class].to_bool ? "in_class_assignment" : "pre_class_assignment") + "=", @assignment)
            @lesson.save!
          end
          format.html { redirect_to (params[:redirect].blank? ? course_path(@course) : params[:redirect]),
            flash: {success: 'Assignment was successfully created.'} }
        else
          @assignment.assignment_questions.build
          format.html { render action: 'new' }
        end
      end
    end
  end

  # PATCH/PUT
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to (params[:redirect].blank? ? course_path(@course) : params[:redirect]),
          flash: {success: 'Assignment was successfully updated.'} }
      else
        @assignment.assignment_questions.build
        format.html { render action: 'edit' }
      end
    end
  end

  # POST
  def turn_in
    final = (params[:commit]=="Submit Final Answers")
    if @assignment.turn_in(params[:questions], current_user, final)
      if final
        flash[:success] = "You have turned in #{@assignment.name}."
      else
        flash[:notice] = "You have saved a draft of #{@assignment.name}."
      end
    else
      flash[:error] = "You are not allowed to turn in #{@assignment.name}."
    end
    redirect_to @assignment
  end

  # GET OR POST
  def grade
    if request.post?
      @assignment.maximum_grade = params[:maximum_grade]
      @assignment.grades_released = (params[:grades_released].blank? ? false : true)
      @assignment.save!
      params[:grades].each do |k, v|
        AssignmentQuestionGrade.find(k).update_attributes!(v)
      end
      flash.now[:success] = "You have successfully saved these grades."
    end
  end

  # GET OR POST
  def grade_matrix
    if request.post?
      Assignment.transaction do
        @assignment.grades_released = (params[:grades_released].blank? ? false : true)
        @assignment.save!
        if params[:aqgs].present?
          params[:aqgs].each do |k, v|
            AssignmentQuestionGrade.find(k).update_attributes!(v)
          end
        end
        if params[:course_students].present?
          params[:course_students].each do |k, v|
            cs = CourseStudent.find(k)
            ag = AssignmentGrade.where(assignment_id: @assignment.id, course_student_id: cs.id).first_or_create
            ag.update_attributes!(v)
          end
        end
      end
      flash.now[:success] = "You have successfully saved these grades."
    end
  end

  # GET
  def view_grades
  end

  private
    def set_assignment_and_course
      @assignment = Assignment.find(params[:id])
      @course = @assignment.course
    end

    def set_course
      @course = Course.find(params[:course_id] || params[:assignment][:course_id])
    end

    def assignment_params
      params.require(:assignment).permit(:course_id, :name, :active_at, :due_at,
          :percent_of_grade, :maximum_grade, :students_can_submit,
          assignment_questions_attributes: [:id, :question, :points, :order_number, :_destroy])
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :redirect, params[:redirect] %>

  <%= f.hidden_field :course_id %>

  <% if @lesson %>
    <%= hidden_field_tag :lesson_id, params[:lesson_id] %>
    <%= hidden_field_tag :in_class, params[:in_class] %>

  <% else %>
    <%= f.label :name do %>
      <span class="field-label">Name</span> <%= f.text_field :name, required: true %>
    <% end %>

    <%= f.label :active_at do %>
      <span class="field-label">Open Date/Time</span> <%= f.text_field :active_at, required: true, value: db_datetime_string(@assignment.active_at) %>
      <span class="help-inline">e.g. "<%= Date.today %> 14:00"</span>
    <% end %>

    <%= f.label :due_at do %>
      <span class="field-label">Due Date/Time</span> <%= f.text_field :due_at, required: true, value: db_datetime_string(@assignment.due_at) %>
      <span class="help-inline">e.g. "<%= Date.today %> 14:00"</span>
    <% end %>
  <% end %>

  <%= f.label :percent_of_grade do %>
    <span class="field-label">% of Final Grade</span> <%= f.text_field :percent_of_grade, required: true, class: "input-small" %>
    <span class="help-inline">%</span>
  <% end %>

  <%= f.label :maximum_grade do %>
    <span class="field-label">Maximum Points</span> <%= f.text_field :maximum_grade, class: "input-small" %>
    <span class="help-inline">(in case question points total more than you want to award)</span>
  <% end %>

  <%= f.label :students_can_submit do %>
    <span class="field-label">Students Submit?</span> <%= f.check_box :students_can_submit %>
  <% end %>

  <h3>Questions</h3>

  <p class="lead">If you would like to add formatting (bold, bullets, etc) to your questions, you can write them
    <a target="blank" href="https://daringfireball.net/projects/markdown/basics">using Markdown.</a></p>

  <% i = 0 %>
  <div class="associations">
    <%= f.fields_for :assignment_questions do |ff| %>
      <div class="association container">
        <div class="row">
          <div class="span2">
            <%= ff.label :order_number do %>
              <strong class="small-field-label">Q #</strong> <%= ff.text_field :order_number, class: "input-small" %>
            <% end %>
            <%= ff.label :points do %>
              <span class="small-field-label">Points</span> <%= ff.text_field :points, class: "input-small" %>
            <% end %>
          </div>
          <div class="span8">
            <%= ff.text_area :question, rows: 6, class: "input-block-level" %>
          </div>
          <div class="span1">
            <% if ff.object.persisted? %>
              <%= link_to 'Delete', nil, class: "btn btn-danger delete-association" %>
              <%= ff.check_box :_destroy, class: "destroy", hidden: true %>
            <% else %>
              <%= link_to 'Delete', nil, class: "btn btn-danger flush-association" %>
            <% end %>
          </div>
        </div>
      </div>
      <% i += 1 %>
    <% end %>
  </div>
  <%= link_to '<i class="fa fa-plus"></i> Add Question'.html_safe, nil, class: "btn btn-mini btn-success new-association", "data-index" => i %>

  <div class="actions">
    <%= f.submit "Save Assignment and Questions", class: "btn" %>
  </div>
<% end %>

app/views/assignments/_grading_header.html.erb
<% status = @assignment.status(current_user)%>

<p><%= link_to back_arrow + "Back to #{@assignment.course_code_and_name}", @assignment.course %></p>

<div class="pull-right">
  <span class="muted">Switch Mode<span class="text-error"> (save first!)</span>:</span>
  <div class="btn-group">
    <% if @assignment.students_can_submit %>
      <%= link_to "Anonymous", grade_assignment_path(@assignment), class: "btn #{mode=='Anonymous' ? 'btn-success' : '' }" %>
      <%= link_to "Named", grade_assignment_path(@assignment, mode: "Named"), class: "btn #{mode=='Named' ? 'btn-success' : '' }" %>
    <% end %>
    <%= link_to "Matrix", grade_matrix_assignment_path(@assignment), class: "btn #{mode=='Matrix' ? 'btn-success' : '' }" %>
    <%= link_to "Report", view_grades_assignment_path(@assignment), class: "btn #{mode=='Report' ? 'btn-success' : '' }" %>
  </div>
</div>

<h2><%= @assignment.name %></h2>

<p class="<%= status.text_class %>">
  <span class="label <%= status.label_class %>"><%= status.name %></span>
  Due <%= date_abbreviation(@assignment.due_at) %> at <%= time_abbreviation(@assignment.due_at) %>.
  <% if @assignment.grades_released.blank? %>
    You have NOT yet released these grades.
  <% else %>
    These grades have been released.
  <% end %>
</p>

app/views/assignments/_row_buttons.html.erb
<% if assignment.status(current_user).name != "Future" %>
  <%= link_to '<i class="fa fa-edit" title="Take Assignment"></i>'.html_safe, assignment_path(assignment) %>

<% else %>
  <i class="fa fa-edit muted" title="Take Assignment"></i>
<% end %>

<% if current_user && current_user.teaching?(assignment.course) %>
  <% if assignment.status(current_user).name == "Future" %>
    <i class="fa fa-legal muted"></i>
    <i class="fa fa-bar-chart-o muted"></i>
  <% else %>
    <% if assignment.students_can_submit %>
      <%= link_to '<i class="fa fa-legal" title="Grade Assignment"></i>'.html_safe, grade_assignment_path(assignment) %>
    <% else %>
      <%= link_to '<i class="fa fa-legal" title="Grade Assignment"></i>'.html_safe, grade_matrix_assignment_path(assignment) %>
    <% end %>
    <%= link_to '<i class="fa fa-bar-chart-o" title="View Grades"></i>'.html_safe, view_grades_assignment_path(assignment) %>
    <%= link_to '<i class="fa fa-calendar-o" title="View Grades"></i>'.html_safe, "#calendar-modal", "data-toggle" => "modal"  %>

  <% end %>
  <%= link_to 'Edit', edit_assignment_path(assignment), class: "btn btn-mini" %>
<% end %>

app/views/assignments/edit.html.erb
<p><%= link_to back_arrow + "Back to #{@assignment.course_code_and_name}", @assignment.course %></p>

<h2>Editing <%= @assignment.name %> </h2>

<%= render 'form' %>

app/views/assignments/grade.html.erb
<%= render partial: "grading_header", locals: {mode: params[:mode] || "Anonymous"} %>

<%= form_tag grade_assignment_path(@assignment) do %>

  <% if params[:mode].present? %>
    <%= hidden_field_tag "mode", params[:mode] %>
  <% end %>

  <% @assignment.assignment_questions.each_with_index do |q, i| %>
    <p class="lead">Question <%= i+1 %> (<%= q.points %> points):</p>
    <%= markdown(q.question) %>

    <% answers = q.assignment_question_grades.submitted %>
    <% answers = answers.shuffle unless params[:mode] == "Named" %>
    <% answers.each_with_index do |aqg, j| %>
      <div class="row">
        <div class="span6 muted divided">
          <p><strong>Answer <%= i+1 %> - <%= params[:mode]=="Named" ? aqg.full_name : j+1 %></strong></p>
          <%= simple_format(aqg.answer) %>
        </div>
        <div class="span6 muted divided">
          <p><strong>Grade for Answer <%= i+1 %>-<%= j+1 %></strong></p>
          <p>
            <span class="field-label">Points (out of <%= q.points %>)</span>
            <%= text_field_tag "grades[#{aqg.id}][grade]", aqg.grade, class: "input-small" %>
          </p>
          <p>
            <span class="field-label">Comments</span>
            <%= text_area_tag("grades[#{aqg.id}][comments]", aqg.comments, rows: 8, class: "input-xlarge") %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

  <p>
    <span class="field-label">Maximum Grade</span>
    <%= text_field_tag "maximum_grade", @assignment.maximum_grade, class: "input-small" %>
  </p>

  <p>
    <span class="field-label">Release Grades?</span>
    <%= check_box_tag "grades_released", "Yes", @assignment.grades_released %>
  </p>

  <p><%= submit_tag "Save Scores and Comments", class: "btn" %></p>

<% end %>

app/views/assignments/grade_matrix.html.erb
<%= render partial: "grading_header", locals: {mode: "Matrix"} %>

<%= form_tag grade_matrix_assignment_path(@assignment) do %>

  <p class="muted">An N/A will appear for a question if a student has not submitted an answer.</p>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <% @assignment.assignment_questions.each do |aq| %>
          <td>
            <strong>Q<%= aq.order_number %></strong>
            <span class="muted">(of <%= aq.points %>)</span></td>
        <% end %>
        <th>Total Override</th>
        <th>Turned In?</th>
      </tr>
    </thead>

    <tbody>
      <% @course.course_students.each do |cs| %>
        <% ag = @assignment.has_been_answered_by(cs.student) %>
        <tr>
          <td><%= cs.full_name %></td>
            <% @assignment.assignment_questions.each do |aq| %>
              <td>
                <% if (aqg = aq.assignment_question_grade_for(ag)) %>
                  <%= text_field_tag "aqgs[#{aqg.id}][grade]", aqg.grade, class: "input-small" %>
                <% else %>
                  <span class="muted">N/A</span>
                <% end %>
              </td>
            <% end %>
          <td>
            <%= text_field_tag "course_students[#{cs.id}][final_grade]", (ag ? ag.final_grade : nil), class: "input-small" %>
          </td>
          <td>
            <% if ag.blank? || ag.submitted_at.blank? %>
              <%= check_box_tag "course_students[#{cs.id}][submitted_at]", Time.now, false %>
            <% else %>
              Yes
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <span class="field-label">Release Grades?</span>
    <%= check_box_tag "grades_released", "Yes", @assignment.grades_released %>
  </p>

  <p><%= submit_tag "Save Scores", class: "btn" %></p>

<% end %>

app/views/assignments/new.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>New Assignment for <%= @course.code_and_name %></h2>

<% if @lesson %>
  <p class="lead text-success">
    <%= @lesson.activity_name(params[:in_class].to_bool) %>
  </p>
<% end %>

<%= render 'form' %>

app/views/assignments/show.html.erb
<% grade = @assignment.has_been_answered_by(current_user) %>
<% can_turn_in = @assignment.can_be_turned_in_by(current_user) %>
<% status = @assignment.status(current_user)%>

<p><%= link_to back_arrow + "Back to #{@assignment.course_code_and_name}", @assignment.course %></p>

<% if grade && @assignment.grades_released %>
  <h2 class="float-right"><small>Your Grade:</small> <%= @assignment.letter_grade_for(current_user) %>
    <small>(<%= int_if_possible(grade.grade) %>)</small></h2>
<% end %>

<h2><%= @assignment.name %></h2>


<p class="<%= status.text_class %>">
  <span class="label <%= status.label_class %>"><%= status.name %></span>
  Due <%= date_abbreviation(@assignment.due_at) %> at <%= time_abbreviation(@assignment.due_at) %>
</p>


<% if status.name=="In Progress" && current_user && !@assignment.students_can_submit %>
  <p class="text-warning">This assignment will be completed by the instructor, and can not be submitted directly by students.</p>
<% end %>


<% if grade %>
  <% if grade.submitted_at.blank? %>
    <p class="text-error">The answers below have not yet been turned in.</p>
  <% elsif @assignment.grades_released.blank? %>
    <p class="text-warning">Your answers have not yet been graded.  Please check back later.</p>
  <% end %>
<% end %>


<% if @assignment.assignment_questions.blank? %>
  <p class="muted">There are no questions for this assignment.</p>
<% else %>

  <%= form_tag turn_in_assignment_path(@assignment) do %>

    <% @assignment.assignment_questions.each_with_index do |q, i| %>
      <% answer = (grade ? grade.answer_on(q) : nil) %>
      <p class="lead">Question <%= i+1 %> (<%= q.points %> points):</p>
      <%= markdown(q.question) %>


      <% if grade %>
        <dl class="dl-horizontal muted">
          <dt>Your answer</dt><dd><%= simple_format(answer || "(No Answer Given)") %></dd>
          <% if @assignment.grades_released %>
            <dt>Your score</dt><dd><%= int_if_possible(grade.grade_on(q)) || "(No Score Given)" %></dd>
            <dt>Instructor comments</dt><dd><%= markdown(grade.comments_on(q) || "(No Comments Given)") %></dd>
          <% end %>
        </dl>
      <% end %>

      <% if can_turn_in %>
        <p><%= text_area_tag("questions[#{q.id}]", answer, rows: 8, class: "input-xxlarge") %></p>
      <% end %>
    <% end %>


    <% if can_turn_in %>
      <p><%= submit_tag "Save Draft", class: "btn" %> <%= submit_tag "Submit Final Answers", class: "btn" %></p>
    <% end %>

  <% end %>

<% end %>

app/views/assignments/view_grades.html.erb
<%= render partial: "grading_header", locals: {mode: "Report"} %>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <% @assignment.assignment_questions.each_with_index do |q, i| %>
      <th>Q<%= i+1 %></th>
    <% end %>
    <th>Total</th>
  </tr>
  <% @course.students.each do |s| %>
    <tr>
      <td><%= s.full_name %></td>
      <td><%= s.email %></td>
      <% total = 0 %>
      <% @assignment.assignment_questions.each do |q| %>
        <td><%= current = s.current_grade_on_question(q) %></td>
        <% total += current.to_f %>
      <% end %>
      <td><%= total %></td>
    </tr>
  <% end %>
</table>