config/routes.rb
Courses::Application.routes.draw do
  get "home/index"
  get "home/requests"
  get "slides/show"

  devise_for :users

  resources :courses do
    member do
      get 'policies'
      post 'policies'
      get 'grade_thresholds'
      post 'grade_thresholds'
      get 'time_cards'
      post 'time_cards'
      post 'enroll'
      post 'register'
      get 'set_feedback_questions'
      patch 'set_feedback_questions'
    end
    collection do
      get 'new_options'
      get 'copy'
      post 'copy'
    end
  end
  resources :course_students do
    member do
      patch 'approve'
      get 'change_email'
      patch 'change_email'
      get 'change_password'
      patch 'change_password'
      get 'change_code'
      patch 'change_code'
    end
  end
  resources :schools
  resources :terms
  resources :users do
    member do
      post 'approve_as_instructor'
      post 'reject_as_instructor'
      get 'new_student'
      post 'create_student'
    end
  end
  resources :assignments do
    member do
      post 'turn_in'
      get 'grade'
      post 'grade'
      get 'grade_matrix'
      post 'grade_matrix'
      get 'view_grades'
    end
  end
  resources :achievements do
    collection do
      get 'award'
      post 'award'
    end
  end
  resources :lessons do
    collection do
      get 'schedule'
    end
  end
  resources :meetings do
    member do
      get 'lead_in_question'
      get 'outline'
      get 'media'
      get 'provide_feedback'
      post 'provide_feedback'
    end
    collection do
      post 'create_many'
    end
  end
  resources :meeting_lessons do
    member do
      delete 'destroy_and_shift'
    end
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user.wants_to_be_instructor && !current_user.instructor %>
  <h2><i class="fa fa-group"></i> Your Instructor Request</h2>
  <p class="lead">Your request is being reviewed.  Please check back later.</p>

  <div class="spacer"></div>
<% end %>

<div class="float-right">
  <div class="spacer"></div>
  <% if params[:show_all] %>
    <%= link_to "<i class='fa fa-undo'></i> Hide older classes".html_safe, "/" %>
  <% else %>
    <%= link_to "<i class='fa fa-history'></i> Show older classes".html_safe, "/?show_all=true" %>
  <% end %>
  <% courses_taught = current_user.courses_taught %>
</div>


<% if current_user.instructor %>
  <h2><i class="fa fa-group"></i> Courses I'm Teaching</h2>

  <% if courses_taught.length > 0 %>
    <% courses_taught.each do |c| %>
      <a href="<%= course_path(c) %>" class="summary-link">
        <%= render partial: "/courses/summary_box", locals: {course: c, header: false} %>
      </a>
      <div class="tiny-spacer"></div>
    <% end %>
  <% else %>
    <p class="lead">Create a course below or ask the instructor of an existing course to add you as a co-instructor.</p>
  <% end %>
  <h3><%= link_to '<i class="fa fa-plus"></i> Create New Course'.html_safe, new_options_courses_path, class: "btn btn-success" %></h3>

  <div class="spacer"></div>
<% end %>


<h2><i class="fa fa-lightbulb-o"></i> Courses I'm Taking</h2>
<% courses_taken = current_user.courses_taken %>

<% if courses_taken.length > 0 %>
  <% courses_taken.each do |c| %>
    <a href="<%= course_path(c) %>">
      <%= render partial: "/courses/summary_box", locals: {course: c, header: false} %>
    </a>
    <div class="tiny-spacer"></div>
  <% end %>

  <div class="spacer"></div>

  <h2><i class="fa fa-pencil"></i> My Assignments</h2>

  <% if (assignments_to_complete = current_user.overdue_or_active_assignments).length > 0 %>
    <table class="table table-hover table-condensed">
      <tr>
        <th>Course</th>
        <th>Due</th>
        <th>Time</th>
        <th>Name</th>
        <th>Status</th>
        <th>% of Grade</th>
        <th></th>
      </tr>
      <% assignments_to_complete.each do |a| %>
      <tr>
        <td style="color: <%= a.course_color %>;"><%= a.course_code_and_name %></td>
        <td><%= date_abbreviation(a.due_at) %></td>
        <td><%= time_abbreviation(a.due_at) %></td>
        <td><%= a.name %></td>
        <td><span class="label <%= a.status(current_user).label_class %>">
          <%= a.status(current_user).name %>
        </span></td>
        <td><%= percentage(a.percent_of_grade) %></td>
        <td>
          <%= render partial: "assignments/row_buttons", locals: {assignment: a} %>
        </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p class="lead">You have no assignments that are currently active or overdue.  Well done!</p>
  <% end %>

<% else %>
  <p class="lead">You are not currently enrolled in any courses.  Consider joining one of these:</p>
  <ul>
    <% Course.example_courses.each do |c| %>
      <li><%= link_to c.code_and_name, course_path(c) %></li>
    <% end %>
  </ul>
<% end %>

app/views/home/requests.html.erb
<% if current_user.admin? %>
  <h2><i class="fa fa-thumbs-up"></i> Instructor Requests</h2>
  <% if (requesting_users = User.want_to_be_instructors).length > 0 %>
    <table class="table table-hover table-condensed">
      <tr>
        <th>Name</th>
        <th>E-mail</th>
        <th>Phone</th>
        <th>School</th>
        <th># Courses Taken</th>
        <th>Acct Created</th>
        <th></th>
      </tr>
      <% requesting_users.each do |u| %>
        <tr>
          <td><%= u.full_name %></td>
          <td><%= u.email %></td>
          <td><%= u.phone %></td>
          <td><%= u.school_name %></td>
          <td><%= u.number_of_courses_taken %></td>
          <td><%= u.created_at.to_date %></td>
          <td class="text-right">
            <%= link_to 'Approve', approve_as_instructor_user_path(u), method: :post, class: "btn btn-mini btn-success" %>
            <%= link_to 'Reject', reject_as_instructor_user_path(u), method: :post, class: "btn btn-mini btn-warning" %>
            <%= link_to 'Delete User Entirely', u, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p class="lead">There are no outstanding instructor requests.</p>
  <% end %>
  <div class="spacer"></div>
<% end %>

<% if current_user.instructor? %>
  <h2><i class="fa fa-thumbs-o-up"></i> Recently Enrolled Students</h2>
  <% if (recent_enrollments = current_user.course_enrollments.unapproved).length > 0 %>
    <table class="table table-hover table-condensed">
      <tr>
        <th>Course</th>
        <th>Student Name</th>
        <th>E-mail</th>
        <th></th>
      </tr>
      <% recent_enrollments.each do |cs| %>
        <tr>
          <td style="color: <%= cs.course_color %>;"><%= cs.course_code_and_name %></td>
          <td><%= cs.full_name %></td>
          <td><%= cs.email %></td>
          <td class="text-right">
            <%= link_to 'Accept as-is', approve_course_student_path(cs), method: :patch, class: "btn btn-mini btn-success" %>
            <%= link_to 'Remove from Class', cs, method: :delete, class: "btn btn-mini btn-warning" %>
          </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p class="lead">There are no recently enrolled students to review.</p>
  <% end %>
  <div class="spacer"></div>
<% end %>