config/routes.rb
Courses::Application.routes.draw do
  get "home/index"
  get "home/requests"
  get "slides/show"

  devise_for :users

  resources :courses do
    member do
      get 'policies'
      post 'policies'
      get 'grade_thresholds'
      post 'grade_thresholds'
      get 'time_cards'
      post 'time_cards'
      post 'enroll'
      post 'register'
      get 'set_feedback_questions'
      patch 'set_feedback_questions'
    end
    collection do
      get 'new_options'
      get 'copy'
      post 'copy'
    end
  end
  resources :course_students do
    member do
      patch 'approve'
      get 'change_email'
      patch 'change_email'
      get 'change_password'
      patch 'change_password'
      get 'change_code'
      patch 'change_code'
    end
  end
  resources :schools
  resources :terms
  resources :users do
    member do
      post 'approve_as_instructor'
      post 'reject_as_instructor'
      get 'new_student'
      post 'create_student'
    end
  end
  resources :assignments do
    member do
      post 'turn_in'
      get 'grade'
      post 'grade'
      get 'grade_matrix'
      post 'grade_matrix'
      get 'view_grades'
    end
  end
  resources :achievements do
    collection do
      get 'award'
      post 'award'
    end
  end
  resources :lessons do
    collection do
      get 'schedule'
    end
  end
  resources :meetings do
    member do
      get 'lead_in_question'
      get 'outline'
      get 'media'
      get 'provide_feedback'
      post 'provide_feedback'
    end
    collection do
      post 'create_many'
    end
  end
  resources :meeting_lessons do
    member do
      delete 'destroy_and_shift'
    end
  end

  root 'home#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_course, only: [:show, :edit, :update, :destroy, :policies, :grade_thresholds, :enroll, :register,
                                    :copy, :time_cards, :set_feedback_questions]
  before_action :instructor_only!, only: [:new, :create, :edit, :update, :policies, :grade_thresholds, :enroll, :copy,
                                    :time_cards, :set_feedback_questions]
  before_action :admin_only!, only: [:destroy]

  # GET /courses/new
  def new
    @course = Course.new
    @course.course_instructors.build(course: @course, instructor: current_user, primary: true)
    @course.course_instructors.build
  end

  # GET /courses/new_options
  def new_options
  end

  # GET/POST
  def copy
    if request.post?
      if (new_course = @course.copy(current_user, Term.find(params[:term_id]), params[:include_objects]))
        redirect_to new_course, flash: {success: 'Course was successfully copied.'}
      else
        redirect_to @course, flash: {error: 'Course could not be copied.  Please contact technical support.'}
      end
    end
  end

  # GET /courses/1
  def show
    unless @course.public || (current_user && current_user.participating?(@course))
      redirect_to home_index_path, flash: {error: 'You do not have permission to view this course.'}
    end
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, flash: {success: 'Course was successfully created.'} }
      else
        @course.course_instructors.build
        format.html { render action: 'new' }
      end
    end
  end

  # GET /courses/1/edit
  def edit
    @course.course_instructors.build
  end

  # PATCH/PUT /courses/1
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, flash: {success: 'Course was successfully updated.'} }
      else
        @course.course_instructors.build
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to home_index_url }
    end
  end

  #GET/POST
  def policies
    @course.policies.build
    if request.post?
      if @course.update(course_params)
        redirect_to @course, flash: {success: 'Course policies were successfully updated.'}
      else
        @course.policies.build
        render action: 'policies'
      end
    end
  end

  #GET/POST
  def grade_thresholds
    @course.grade_thresholds.build
    if request.post?
      if @course.update(course_params)
        redirect_to @course, flash: {success: 'Course grade_thresholds were successfully updated.'}
      else
        @course.grade_thresholds.build
        render action: 'grade_thresholds'
      end
    end
  end

  #POST
  def enroll
    student = User.find_by_email(params[:email])
    if student
      if student.enrolled? @course
        redirect_to @course, flash: {error: "Student is already enrolled in this class."}
      else
        @course.course_students.build(student: student, approved: true)
        @course.save!
        redirect_to @course, flash: {success: "Student has been successfully added."}
      end
    else
      redirect_to new_student_user_url(course_id: @course.id, email: params[:email]),
        notice: "E-mail address not found.  Please create a new student."
    end
  end

  #POST
  def register
    student = User.find(params[:student_id])
    if student.enrolled? @course
      redirect_to @course, flash: {error: "You are already enrolled in this class."}
    else
      @course.course_students.build(student: student, approved: false)
      @course.save!
      redirect_to @course, flash: {success: "You have been enrolled in this class, and the instructor has been notified."}
    end
  end

  #GET/POST
  def time_cards
    if request.post?
      if (student = User.where(code: params[:code]).first) && student.enrolled?(@course)
        CourseStudent.where(course: @course, student: student).first.check_in_or_out
      else
        flash[:error] = "This code does not belong to any of the students in this course.  Please try again."
      end
    end
  end

  # GET/PATCH
  def set_feedback_questions
    if request.patch?
      if @course.update(course_params)
        redirect_to @course, flash: {success: 'Feedback questions were successfully updated.'}
      else
        @course.feedback_questions.build
      end
    else
      @course.feedback_questions.build
    end
  end

  private

    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:term_id, :course_code, :name, :period,
          :color, :description, :public, :grading_method,
          :use_daily_questions, :use_time_cards, :use_reveal_slides, :use_meeting_video, :use_course_feedback,
          course_instructors_attributes: [:id, :primary, :instructor_id, :_destroy],
          policies_attributes: [:id, :name, :order_number, :description, :_destroy],
          grade_thresholds_attributes: [:id, :grade, :letter, :_destroy],
          feedback_questions_attributes: [:id, :question, :order_number, :_destroy])
    end

end

app/views/courses/_modal_add_student.html.erb
<div id="student-modal" class="modal hide fade">
  <%= form_tag enroll_course_path, method: :post do %>
    <div class="modal-header">
      <h3>Add a Student to <%= @course.course_code %></h3>
    </div>
    <div class="modal-body">
      <%= hidden_field_tag :id, @course.id %>
      <span class="field-label"><%= label_tag :email, "Email" %></span>
      <div class="input-prepend">
        <span class="add-on">@</span>
        <%= text_field_tag :email, nil, type: "email", required: true %>
      </div>
    </div>
    <div class="modal-footer">
      <a class="btn" data-dismiss="modal">Close</a>
      <%= submit_tag "Add Student", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/courses/_modal_modal_modal.html.erb
<div id="calendar-modal" class="modal hide fade">
  <%= form_tag enroll_course_path, method: :post do %>
    <div class="modal-header">
      <h3>Calendar stuff <%= @course.course_code %></h3>
    </div>
    <div class="modal-body">
      <%= hidden_field_tag :id, @course.id %>
      <span class="field-label"><%= label_tag :starts_on, "Starts on" %></span>
      <div class="input-prepend">
        <span class="add-on">@</span>
        <%= text_field_tag :starts_on, nil, type: "Starts on", required: true %>
      </div><br>

      <span class="field-label"><%= label_tag :ends_on, "Ends on" %></span>
      <div class="input-prepend">
        <span class="add-on">@</span>
        <%= text_field_tag :ends_on, nil, type: "Ends on", required: true %>
      </div><br>

      <span class="field-label"><%= label_tag :calendar, "Calendar" %></span>
      <div class='col-sm-6'>
          <input type='text' class="form-control" id='datetimepicker4'/>
      </div>
      <script type="text/javascript">
          $(function () {
              $('#datetimepicker4').datetimepicker();
          });
      </script>


    </div>



    <div class="modal-footer">
      <a class="btn" data-dismiss="modal">Close</a>
      <%= submit_tag "Calendar", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/courses/_summary_box.html.erb
<style>
#course-<%= course.id %> {
  background: <%= course.color %>;
  background-image: -webkit-linear-gradient(45deg, <%= course.color %> 0%,#FFFFFF 100%);
  background-image: -moz-linear-gradient(45deg, <%= course.color %> 0%,#FFFFFF 100%);
  background-image: -ms-linear-gradient(45deg, <%= course.color %> 0%,#FFFFFF 100%);
  background-image: -o-linear-gradient(45deg, <%= course.color %> 0%,#FFFFFF 100%);
  background-image: linear-gradient(45deg, <%= course.color %> 0%,#FFFFFF 100%);
}
</style>
<div class="container course-summary <%= header ? 'course-summary-fixed': 'course-summary-small' %>" id="course-<%= course.id %>">
  <div class="row">
    <div class="span9">
      <h<%= 3-(header ? 1 : 0) %>>
        <%= course.code_and_name %>
      </h<%= 3-(header ? 1 : 0) %>>
      <p class="lead muted">
        <% if course.old? %>
          <i class="fa fa-clock-o"></i> <%= course.term.name %>
        <% else %>
          <%= course.instructor_names %>
        <% end %>
      </p>
      <% if header %>
        <nav class="navbar smooth-nav">
          <div class="navbar-inner">
            <ul class="nav">
              <li><%= link_to "Description", '#anchor-description' %></li>
              <li class="divider-vertical"></li>
              <% if current_user && current_user.teaching?(@course) %>
                <li><%= link_to "Students", '#anchor-students' %></li>
                <li class="divider-vertical"></li>
              <% end %>
              <% if @course.achievement_grading? %>
                <li><%= link_to "Achievements", '#anchor-achievements' %></li>
              <% else %>
                <li><%= link_to "Assignments", '#anchor-assignments' %></li>
              <% end %>
              <li class="divider-vertical"></li>
              <li><%= link_to "Lessons", '#anchor-lessons' %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Policies", '#anchor-policies' %></li>
            </ul>
          </div>
        </nav>
      <% end %>
    </div>
    <div class="span2 text-center">
      <% if current_user %>
        <% if current_user.enrolled?(course) %>
          <% if course.achievement_grading? %>
            <br />
            <h<%= 3-(header ? 1 : 0) %>>
              <%= current_user.letter_grade(course) %> <small>(<%= number_with_precision(current_user.grade(course), precision: 0) %> pts)</small>
            </h<%= 3-(header ? 1 : 0) %>>
          <% else %>
            <% percent_graded = percentage(current_user.percent_graded(course)) -%>
            <h<%= 3-(header ? 1 : 0) %>>
              <%= current_user.letter_grade(course) %> <small>(<%= number_with_precision(current_user.grade(course), precision: 1) %>)</small>
            </h<%= 3-(header ? 1 : 0) %>>
            <% if header %>
              <small class="muted">Possible:
                <%= number_with_precision(current_user.min_grade(course), precision: 1) %> -
                <%= number_with_precision(current_user.max_grade(course), precision: 1) %>
              </small>
            <% end %>
            <div class="progress">
              <div class="bar bar-success" style="width: <%= percent_graded %>;"></div>
            </div>
            <small class="progress-overlay"><%= percent_graded %> graded</small>
          <% end %>
        <% elsif current_user.teaching?(course) %>
          <% unless course.achievement_grading? %>
            <% percent_graded = percentage(course.assignment_statuses(current_user).first.percent) -%>
            <% percent_ungraded = percentage(course.assignment_statuses(current_user).second.percent) -%>
            <div class="progress progress-striped">
              <div class="bar bar-success" style="width: <%= percent_graded %>;"></div>
              <div class="bar bar-danger" style="width: <%= percent_ungraded %>;"></div>
            </div>
            <small class="muted"><%= percent_graded %> graded</small><br/>
            <small class="<%= percent_ungraded == '0%' ? 'muted' : 'text-error' %>"><%= percent_ungraded %> waiting to be graded</small>
          <% end %>
        <% else %>
          <br/>
          <%= link_to "<i class='fa fa-plus'></i>".html_safe + " Enroll in #{course.course_code}",
            register_course_path(id: @course.id, student_id: current_user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      <% else %>
        <br/>
        <p class="muted">Want to enroll?<br/><%= link_to "Sign up for Coursyl", new_user_registration_path %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>Course Details</h2>

<%= render 'form' %>

app/views/courses/new.html.erb
<p><%= link_to back_arrow + "Cancel and Return to Home", home_index_path %></p>

<h2>New Course</h2>

<%= render 'form' %>

app/views/courses/new_options.html.erb
<p><%= link_to back_arrow + "Cancel and Return to Home", home_index_path %></p>

<h2>New Course Options</h2>

<div class="row">
  <div class="span4 well min-height">
    <%= form_tag copy_courses_path, method: "get" do %>
      <h4>Option 1: Copy an Existing Course</h4>
      <div class="copy-course">
        <%= select_tag :id, options_from_collection_for_select(Course.all, 'id', 'code_and_name_and_term') %>
      </div>
      <%= submit_tag "Copy from Existing Course", class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="span4 well min-height">
    <h4>Option 2: New Course from Scratch</h4>
    <div class="copy-course"></div>
    <%= link_to 'Create New Course', new_course_path, class: "btn btn-success copy-course-button" %>
  </div>
</div>

app/views/courses/set_feedback_questions.html.erb
<p><%= link_to back_arrow + "Back to #{@course.code_and_name}", @course %></p>

<h2>Course Feedback Questions</h2>

<%= form_for @course, url: set_feedback_questions_course_path do |f| %>
  <% if @course.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class="lead">Students will answer all of these questions once per class meeting time.  Their answers will be
    given on a Lykert Scale from 0 to 10, where 10 is best and 0 is worst.</p>

  <% i = 0 %>
  <div class="associations">
    <%= f.fields_for :feedback_questions do |ff| %>
      <div class="association container">
        <div class="row">
          <div class="span2">
            <%= ff.label :order_number do %>
              <strong class="small-field-label">Q #</strong> <%= ff.text_field :order_number, class: "input-small" %>
            <% end %>
          </div>
          <div class="span8">
            <%= ff.text_area :question, rows: 6, class: "input-block-level" %>
          </div>
          <div class="span1">
            <% if ff.object.persisted? %>
              <%= link_to 'Delete', nil, class: "btn btn-danger delete-association" %>
              <%= ff.check_box :_destroy, class: "destroy", hidden: true %>
            <% else %>
              <%= link_to 'Delete', nil, class: "btn btn-danger flush-association" %>
            <% end %>
          </div>
        </div>
      </div>
      <% i += 1 %>
    <% end %>
  </div>
  <%= link_to '<i class="fa fa-plus"></i> Add Question'.html_safe, nil, class: "btn btn-mini btn-success new-association", "data-index" => i %>

  <div class="actions">
    <%= f.submit "Save Feedback Questions", class: "btn" %>
  </div>

<% end %>

app/views/courses/show.html.erb
<% assignment_statuses = @course.assignment_statuses(current_user) -%>

<%= render partial: "summary_box", locals: {course: @course, :header => true} %>




<section id="first-section">
  <a id="anchor-description" class="anchor-course"></a>
  <% if current_user && current_user.teaching?(@course) %>
    <h3 class="float-right float-right-header"><%= link_to 'Edit Course Details', edit_course_path(@course), class: "btn" %></h3>
  <% end %>
  <h3><i class="fa fa-lightbulb-o"></i> Course Description</h3>
  <p class="muted">Meeting Times: <%= @course.period %></p>
  <%= markdown(@course.description) %>
</section>




<% if current_user && current_user.teaching?(@course) %>
  <% last_assignment = @course.last_assignment %>
  <% next_assignment = @course.next_assignment %>
  <section>
    <a id="anchor-students" class="anchor-course"></a>
    <% if @course.students.blank? %>
      <h3 class="float-right float-right-header">
        <a href="#student-modal" class="btn btn-success" data-toggle="modal">
          <i class="fa fa-plus"></i> Add Student
        </a>
      </h3>
    <% elsif @course.use_time_cards %>
      <h3 class="float-right float-right-header"><%= link_to 'Student Check-in/Check-out', time_cards_course_path(@course), class: "btn" %></h3>
    <% end %>

    <%= render partial: 'modal_add_student' %>
    <%= render partial: 'modal_modal_modal' %>

    <h3><i class="fa fa-group"></i> Students</h3>
    <% if @course.students.present? %>
      <table class="table table-hover table-condensed">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <% if last_assignment %><th>Last Assignment <i class="fa fa-question-circle muted" title="<%= last_assignment.name %>"></i></th><% end %>
          <% if next_assignment %><th>Next Assignment <i class="fa fa-question-circle muted" title="<%= next_assignment.name %>"></i></th><% end %>
          <% if @course.use_time_cards %>
            <th>Hrs this Wk</th>
            <th>Total Hrs</th>
          <% end %>
          <th>Overall Grade</th>
          <td class="text-right">
            <a href="#student-modal" class="btn btn-mini btn-success" data-toggle="modal">
              <i class="fa fa-plus"></i> Add Student
            </a>
          </td>
        </tr>
        <% @course.students.each do |student| %>
          <% last_status = last_assignment.status(student) if last_assignment %>
          <% next_status = next_assignment.status(student) if next_assignment %>
          <% cs = student.course_student_for(@course)%>
          <tr>
            <td><%= student.full_name %></td>
            <td><%= student.email %></td>
            <% if last_assignment %><td><span class="label <%= last_status.label_class %>"><%= last_status.name %></span></td><% end %>
            <% if next_assignment %><td><span class="label <%= next_status.label_class %>"><%= next_status.name %></span></td><% end %>
            <% if @course.use_time_cards %>
              <td><%= number_with_precision(cs.time_this_week, precision: 1) %></td>
              <td><%= number_with_precision(cs.total_time, precision: 1) %></td>
            <% end %>
            <td><%= number_with_precision(cs.grade, precision: 1) %></td>
            <td class="text-right">
              <i class="fa fa-bar-chart-o muted" title="View Grades"></i>
              <% if @course.use_time_cards %>
                <%= link_to '<i class="fa fa-barcode" title="Change Student Code"></i>'.html_safe, change_code_course_student_path(cs) %>
              <% end %>
              <%= link_to '<i class="fa fa-random" title="Change Student Email Address"></i>'.html_safe, change_email_course_student_path(cs) %>
              <%= link_to '<i class="fa fa-key" title="Change Student Password"></i>'.html_safe, change_password_course_student_path(cs) %>
              <%= link_to '<i class="fa fa-times-circle-o" title="Remove Student from Course"></i>'.html_safe, cs, method: :delete,
                data: { confirm: "Are you sure that you would like to remove #{student.full_name} from the course?" } %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p class="lead">There are no students in this course.</p>
    <% end %>
  </section>
<% end %>



<% if @course.achievement_grading? %>
  <section>
    <a id="anchor-achievements" class="anchor-course"></a>
    <% if current_user && current_user.teaching?(@course) %>
      <h3 class="float-right float-right-header">
        <% if @course.achievements.blank? %>
          <%= link_to '<i class="fa fa-plus"></i> Add Achievement'.html_safe,
              new_achievement_path(course_id: @course.id),
              class: "btn btn-success" %>
        <% else %>
          <%= link_to 'Award Achievements',
              award_achievements_path(course_id: @course.id),
              class: "btn" %>
        <% end%>
      </h3>
    <% end %>
    <h3><i class="fa fa-certificate"></i> Achievements</h3>
    <% if @course.achievements.present? %>
      <table class="table table-condensed">
        <% if current_user && current_user.teaching?(@course) %>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <td class="text-right">
              <%= link_to '<i class="fa fa-plus"></i> New Achievement'.html_safe,
                  new_achievement_path(course_id: @course.id),
                  class: "btn btn-mini btn-success" %>
            </td>
          </tr>
        <% end %>
        <% @course.achievements.each do |a| %>
          <% disabled = (current_user && current_user.enrolled?(@course) && !current_user.awarded?(a))%>
          <tr>
            <td><%= badge(a, muted: disabled)%></td>
            <td><div class="<%= disabled ? 'muted' : 'bold' %>"><%= a.points %> pts</div></td>
            <td><%= a.category %></td>
            <td><strong><%= a.name %></strong><br/><span class="muted"><%= a.description %></span></td>

            <% if current_user && current_user.teaching?(@course) %>
              <td class="text-right">
                <%= link_to 'Edit', edit_achievement_path(a), class: "btn btn-mini" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p class="lead">There are no achievements for this course.</p>
    <% end %>
  </section>



<% else %>
  <section>
    <a id="anchor-assignments" class="anchor-course"></a>
    <% if current_user && current_user.teaching?(@course) &&
        @course.assignments.blank? && @course.assignment_grading? %>
      <h3 class="float-right float-right-header">
        <%= link_to '<i class="fa fa-plus"></i> New Assignment'.html_safe,
            new_assignment_path(course_id: @course.id),
            class: "btn btn-success" %>
      </h3>
    <% end %>
    <h3><i class="fa fa-pencil"></i> Assignments</h3>
    <% if @course.assignments.present? %>
      <div class="progress progress-striped">
        <% assignment_statuses.each do |status| %>
        <div class="bar <%= status.bar_class %>"
          style="width: <%= percentage(status.percent) %>;"></div>
        <% end %>
      </div>
      <ul class="inline text-center">
        <% assignment_statuses.each do |status| %>
        <li class="<%= status.text_class %>">
          <span class="label <%= status.label_class %>">
            <%= status.name %>
          </span>
          <%= percentage(status.percent) %>
        </li>
        <% end %>
      </ul>
      <table class="table table-hover table-condensed">
        <tr>
          <th>Due</th>
          <th>Time</th>
          <th>Name</th>
          <th>Status</th>
          <% if current_user && current_user.enrolled?(@course) %>
            <th>My Grade</th>
          <% end %>
          <th>% of Course</th>
          <td class="text-right">
            <% if current_user && current_user.teaching?(@course) && @course.assignment_grading? %>
              <%= link_to '<i class="fa fa-plus"></i> New Assignment'.html_safe,
                  new_assignment_path(course_id: @course.id),
                  class: "btn btn-mini btn-success" %>
            <% end %>
          </td>
        </tr>
        <% @course.assignments.each do |a| %>
          <tr>
            <td><%= date_abbreviation(a.due_at) %></td>
            <td><%= time_abbreviation(a.due_at) %></td>
            <td><%= a.name %></td>
            <td><span class="label <%= a.status(current_user).label_class %>">
              <%= a.status(current_user).name %>
            </span></td>
            <% if current_user && current_user.enrolled?(@course) %>
              <td><%= int_if_possible(current_user.grade_on_assignment(a)) %></td>
            <% end %>
            <td><%= percentage(a.percent_of_grade) %></td>
            <td class="text-right">
              <%= render partial: "/assignments/row_buttons", locals: {assignment: a} %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p class="lead">
        There are no assignments for this course.
      </p>
    <% end %>
  </section>
<% end %>


<section>
  <a id="anchor-lessons" class="anchor-course"></a>
  <% if current_user && current_user.teaching?(@course) %>
    <h3 class="float-right float-right-header">
      <% if @course.use_course_feedback %>
        <%= link_to 'Set Feedback Questions', set_feedback_questions_course_path(@course), class: "btn" %>
      <% end %>
      <%= link_to 'Schedule Lessons', schedule_lessons_path(course_id: @course.id), class: "btn" %>
    </h3>
  <% end %>
  <h3><i class="fa fa-clock-o"></i> Meeting Times and Lessons</h3>

  <% if @course.meeting_lessons.present? %>
    <div id="lesson-tree-anchor"></div>
    <div id="lesson-tree-wrapper">
      <div id="lesson-tree" class="well"></div>
    </div>
    <script>
      var tree = new TreeGenerator(<%= @course.lesson_tree.to_json.html_safe %>);
      tree.buildTree("#lesson-tree");
      TreeHandler.colorNodesToPresent();
    </script>
  <% end %>

  <% if @course.meetings.present? %>
    <table class="table table-hover table-condensed">
      <tr>
        <th>Day</th>
        <th>Date</th>
        <th>Time</th>
        <th>Lessons</th>
        <% if @course.use_course_feedback && current_user && current_user.teaching?(@course) %>
          <% @course.feedback_questions.each do |fq| %>
            <th>F<%= fq.order_number %> <i class="fa fa-question-circle muted" title="<%= fq.question %>"></i></th>
          <% end %>
        <% end %>
        <th></th>
      </tr>
      <% @course.meetings.each do |m| %>
        <tr heldat="<%= m.held_at_integer %>" class="node">
          <td><strong><%= weekday_abbreviation(m.held_at) %></strong></td>
          <td><%= date_abbreviation(m.held_at) %></td>
          <td><%= time_abbreviation(m.held_at) %></td>
          <td><%= m.lesson_names %></td>
          <% if @course.use_course_feedback && current_user && current_user.teaching?(@course) %>
            <% @course.feedback_questions.each do |fq| %>
              <td><%= number_with_precision(m.average_feedback(fq), precision: 1) %></td>
            <% end %>
          <% end %>
          <td class="text-right">
            <%= render partial: "/meetings/row_buttons", locals: {meeting: m} %>
          </td>
        </tr>
      <% end %>
    </table>
    <div id="lesson-bottom-anchor"></div>
  <% else %>
    <p class="lead">No lessons have been scheduled for this course.</p>
  <% end %>
</section>




<section>
  <a id="anchor-policies" class="anchor-course"></a>
  <% if current_user && current_user.teaching?(@course) %>
    <h3 class="float-right float-right-header">
      <%= link_to 'Edit Grading Scale', grade_thresholds_course_path(@course), class: "btn" %>
      <%= link_to 'Edit Course Policies', policies_course_path(@course), class: "btn" %>
    </h3>
  <% end %>
  <h3><i class="fa fa-comments-o"></i> Course Policies</h3>
  <% if @course.policies.present? || @course.grade_thresholds.present? %>
    <dl class="dl-horizontal">
      <% unless @course.grade_thresholds.blank? %>
        <dt>Grading Scale</dt>
        <dd>The following are the possible letter grades in the course:
          <ul>
            <% @course.grade_thresholds.each do |t| %>
              <li><%= t.letter %>: <%= int_if_possible(t.grade) %> and above</li>
            <% end %>
          </ul>
        </dd>
      <% end %>

      <% unless @course.grade_thresholds.blank? %>
        <% @course.policies.each do |p| %>
          <dt><%= p.name %></dt>
          <dd><%= markdown(p.description) %></dd>
        <% end %>
      <% end %>
    </dl>
  <% else %>
    <p class="lead">There are no policies for this course.</p>
  <% end %>
</section>